### ISSUE TITLE
Exception in Dicom.Native for Linux

### ISSUE THREAD

**Issue by jaime-olivares** [Efferent-Health/fo-dicom#1]
mia-san commented 16 hours ago
hi, @jaime-olivares.I've just updated my project to use 4.0.9-efferent, following simple program doesn't work anymore.it works with 4.0.8-efferent.I have fo-dicom.NetCoreHP and fo-dicom.DrawingHP installed,tested Windows10 x64 and Linux x64, same results.I've also copied Dicom.Native* file into several places, no luck.any idea?

````
      private static void Main(string[] args) {
      ImageManager.SetImplementation(WinFormsImageManager.Instance);
      var image = new DicomImage("jpeg-lossless.dcm");
      try
     {
         using (var iimage = image.RenderImage())
         {
             iimage.AsSharedBitmap();
             Console.WriteLine("OK");
         }
     }
     catch (Exception ex)
     {
         Console.WriteLine(ex.ToString());
     }
      Console.ReadLine(); 
}
````

causes 

````
Dicom.Imaging.Codec.DicomCodecException: Decoding dataset with transfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression is not supported.
    at Dicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
    at Dicom.Imaging.Codec.DicomTranscoder.DecodePixelData(DicomDataset dataset, Int32 frame)
    at Dicom.Imaging.GrayscaleRenderOptions.FromMinMax(DicomDataset dataset)
    at Dicom.Imaging.GrayscaleRenderOptions.FromDataset(DicomDataset dataset)
    at Dicom.Imaging.DicomImage.CreatePipelineData(DicomDataset dataset, DicomPixelData pixelData)    at Dicom.Imaging.DicomImage.EstablishPipeline()
    at Dicom.Imaging.DicomImage.GetFrameIndex(Int32 frame)
    at Dicom.Imaging.DicomImage.RenderImage(Int32 frame)    at ConsoleApp2.Program.Main(String[] args)
````

**Comment by jaime-olivares** [comment]
Apparently this issue appeared because the lack of one reference in version 4.0.9, specifically System.ComponentModel.Composition (>= 4.5.0)
You can try by yourself or wait for the incoming patch this weekend.

**Comment by mia-san** [comment]
@jaime-olivares System.ComponentModel.Composition (4.6.0-preview.18571.3 now) seems to make things work again. thank you !!

**Comment by jaime-olivares** [comment]
I have published version 4.0.10 in NuGet:

https://www.nuget.org/packages/fo-dicom.DrawingHP/4.0.10-efferent

https://www.nuget.org/packages/fo-dicom.NetCoreHP/4.0.10-efferent

**Comment by mia-san** [comment]
thank you for publishing.

but above program does not compile with 4.0.10 as following.
it compiles with 4.0.8 or 4.0.9.

> Program.cs(10,65): error CS0012: The type 'ImageManager' is defined in an assembly that is not referenced. You must add a reference to assembly 'Dicom.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3a13f649e28eb09a'.
> Program.cs(16,21): error CS0012: The type 'IImage' is defined in an assembly that is not referenced. You must add a reference to assembly 'Dicom.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3a13f649e28eb09a'.

same happens on both linux and windows.
adding 'official' fo-dicom.netcore package conflicts at Dicom.Core.
adding 'system.componentmodel.composition' does not help this time.

here's my sample project file.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="fo-dicom.DrawingHP" Version="4.0.10-efferent" />
    <PackageReference Include="fo-dicom.NetCoreHP" Version="4.0.10-efferent" />
  </ItemGroup>

</Project>
```

am I missing something ?

**Comment by jaime-olivares** [comment]
The nugget package 4.0.14 seems to be stable now regarding dependencies

**Comment by mia-san** [comment]
thank you for new release.
quick checking, things are working flawlessly :)
great work !!
//

**Comment by mia-san** [comment]
just a quick check, 4.0.20-efferent seems to be working as expected.
thank you for new release !!

**Comment by jaime-olivares** [comment]
Hi, thanks for the validation!
Regarding the sync with development, it is not.
I will need to verify if there won't be any merge issue.

**Comment by jaime-olivares** [comment]
I see you have a lot of contributions to the fo-dicom project. Do you know what else we would need to incorporate our fork into it?
We invested a huge amount on time on this and it is a bummer it cannot be there yet.
We don't have the expertise to to merge everything into fo-dicom but we already have a functional cross-version tested in Linux.

**Comment by mia-san** [comment]
I really love your work, one of my projects heavily depends on your package, greatly helpful.
on the other hand, fo-dicom/development has important bug fixes and improvements.

what about submitting pull-request to fo-dicom project ?
at least sync your development branch to fo-dicom's one?
can I be of any help?

**Comment by jaime-olivares** [comment]
I tried to incorporate the last changes from fo-dicom into the project. 
They are so many and so fundamental that should have changed they version number to 4.1.
I will have to roll-back for now.

**Comment by jaime-olivares** [comment]
@mia-san Please have a look at our new project that supersedes this one: https://github.com/Efferent-Health/Dicom-native
It is not a fo-dicom fork anymore. Just a plugin.

**Comment by mia-san** [comment]
> @mia-san Please have a look at our new project that supersedes this one: https://github.com/Efferent-Health/Dicom-native
> It is not a fo-dicom fork anymore. Just a plugin.

oh, looks promising!!
I'm out for business now, I'd like to take a look ASAP. when I'm back.
thank you !!
//

**Comment by PalminX** [comment]
This is really great, we already did a first try and succeeded in JPEG-LS
decompression under .Net Core.

There were some issues with palette color images which we will look into.

Nevertheless, thanks for your great work!

mia-san <notifications@github.com> schrieb am Sa. 13. Apr. 2019 um 09:19:

**Comment by mia-san** [comment]
> @mia-san Please have a look at our new project that supersedes this one: https://github.com/Efferent-Health/Dicom-native
> It is not a fo-dicom fork anymore. Just a plugin.

just following up.

I've just tried your new package.
I slightly miss AsBitmap etc, but I can live with AsByte.

here's my sample project on gist
https://gist.github.com/mia-san/41fb2812da42aca491d3effbed1d5d6f

thank you very much, @jaime-olivares !!
//
